# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'AzureSC'
    azureContainerRegistry: '{"loginServer":"digivisio2030.azurecr.io", "id" : "/subscriptions/8f69462c-5cef-4c99-b4b2-250f8a0bb0a5/resourceGroups/DigiVisio2030/providers/Microsoft.ContainerRegistry/registries/digivisio2030"}'
    dockerComposeFile: '**/docker-compose.devops.yml'
    action: 'Build services'
    includeSourceTags: true
    includeLatestTag: true
